version: '3.8'

services:
  server:
    build:
      context: .
      target: final
    ports:
      - "8081:8081"
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: my_database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
