http:
  server:
    addr: "0.0.0.0:8081"

db:
  host: db
  port: 5432
  user: postgres
  password: password
  database: my_database
  poolsize: 10
  sslmode: disable

migration:
  path: "./schema/migrations"
  needMigration: true
